services:
  worker:
    image: 127.0.0.1:5000/transcoder/worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    command: celery -A tasks worker --loglevel=info --concurrency=1
    environment:
      CELERY_BROKER: redis://192.168.0.120:6379/0
      CELERY_BACKEND: redis://192.168.0.120:6379/1
    volumes:
      - vol_archives:/watch
      - vol_chunks:/chunks
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri/renderD128

volumes:


  vol_archives:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/archive

  vol_chunks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/chunks

