services:


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - vol_redis:/data
    deploy:
      placement: 
        constraints: 
          - node.hostname == swarm1

  flaskapp:
    image: 127.0.0.1:5000/transcoder/flaskapp
    build:
      context: .                    # was ./flaskapp
      dockerfile: flaskapp/Dockerfile
    restart: always
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    ports:
      - "5005:5000"
    depends_on:
      - redis
    volumes:
      - vol_archives:/watch
      - vol_chunks:/chunks      # ⬅️ GlusterFS mount from host
      - vol_library:/library
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - node.hostname == swarm1

  worker:
    image: 127.0.0.1:5000/transcoder/worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    command: huey_consumer tasks.huey -w 1
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - vol_archives:/watch
      - vol_chunks:/chunks
    deploy:
      replicas: 0

  watchdog:
    image: 127.0.0.1:5000/transcoder/watchdog
    build:
      context: ./watchdog
      dockerfile: Dockerfile
    restart: always
    command: python watcher.py
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
      - flaskapp
    volumes:
      - vol_archives:/watch
    deploy:
      placement: 
        constraints: 
          - node.role == manager



volumes:
  vol_redis:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/transcoder/redis

  vol_archives:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/archive

  vol_library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/library

  vol_chunks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/chunks

