services:


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - vol_redis:/data

  flaskapp:
    image: 127.0.0.1:5000/transcoder/flaskapp
    build:
      context: ./flaskapp
      dockerfile: Dockerfile
    restart: always
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    ports:
      - "5005:5000"
    depends_on:
      - redis
    volumes:
      - vol_archives:/watch
      - /mnt/chunks:/chunks      # ⬅️ GlusterFS mount from host

  worker:
    image: 127.0.0.1:5000/transcoder/worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    command: celery -A tasks worker --loglevel=info --concurrency=1
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - vol_archives:/watch
      - /mnt/chunks:/chunks      # ⬅️ GlusterFS mount from host
    deploy:
      replicas: 0

  watchdog:
    image: 127.0.0.1:5000/transcoder/watchdog
    build:
      context: ./watchdog
      dockerfile: Dockerfile
    restart: always
    command: python watcher.py
    environment:
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/1
    depends_on:
      - redis
      - flaskapp
    volumes:
      - vol_archives:/watch
      - /mnt/chunks:/chunks      # ⬅️ GlusterFS mount from host

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    ports:
      - target: 9100
        published: 9100
        mode: host
    networks:
      - monitoring
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - target: 9090
        published: 9090
        mode: host
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - target: 3000
        published: 3000
        mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      - REDIS_ADDR=redis://192.168.0.120:6379
    ports:
      - target: 9121
        published: 9121
        mode: host
    networks:
      - monitoring
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - target: 8080
        published: 8080
        mode: host
    networks:
      - monitoring
    deploy:
      mode: global


networks:
  monitoring:
    driver: overlay

volumes:

  vol_redis:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/transcoder/redis

  vol_archives:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/archive

  vol_prometheus:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/config/prometheus

configs:
  prometheus_config:
    file: ./prometheus/prometheus.yml