services:
  worker:
    image: 127.0.0.1:5000/transcoder/worker
    env_file: ".env"
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    command: huey_consumer tasks.huey -w 1
    shm_size: "2g"                 # raise from 64MB default
    tmpfs:
      - /dev/shm:size=8g,exec,nosuid,nodev
    volumes:
      - vol_archives:/watch
      - vol_library:/library
      - vol_chunks:/chunks
      - ./:/projects
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri/renderD128
    ports:
      - "8000:8000"

volumes:


  vol_archives:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/archive

  vol_library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/library

  vol_chunks:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.5,nolock,soft
      device: :/volume1/shared/projects/media/chunks
